# Generated by Django 5.2.6 on 2025-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Haunting",
            fields=[
                ("id_haunting", models.AutoField(primary_key=True, serialize=False)),
                ("haunting_type", models.IntegerField(blank=True, null=True)),
                ("haunting_booktext", models.TextField(blank=True, null=True)),
                ("haunting_pagestart", models.IntegerField(blank=True, null=True)),
                ("haunting_pageend", models.IntegerField(blank=True, null=True)),
                ("haunting_storyabstract", models.TextField(blank=True, null=True)),
                ("haunting_storyshort", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "haunting",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Hautingtype",
            fields=[
                (
                    "id_hauntingtype",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("hauntingtype", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hauntingtype",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id_location", models.AutoField(primary_key=True, serialize=False)),
                ("location_name", models.TextField(blank=True, null=True)),
                ("location_street", models.TextField(blank=True, null=True)),
                ("location_housenumber", models.IntegerField(blank=True, null=True)),
                ("location_houseletter", models.TextField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("location_notes", models.TextField(blank=True, null=True)),
                ("location_photo", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "location",
                "managed": True,
            },
        ),
    ]
