# Generated by Django 5.2.6 on 2025-09-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hautingtype",
            new_name="Hauntingtype",
        ),
    ]
