# Generated by Django 5.2.6 on 2025-09-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0002_rename_hautingtype_hauntingtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="haunting",
            name="fk_hauntingtype",
            field=models.ForeignKey(
                blank=True,
                db_column="fk_hauntingtype",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="fk_hauntingtype",
                to="mapping.hauntingtype",
            ),
        ),
        migrations.AddField(
            model_name="haunting",
            name="fk_location",
            field=models.ForeignKey(
                blank=True,
                db_column="fk_location",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="fk_location",
                to="mapping.location",
            ),
        ),
        migrations.AddField(
            model_name="haunting",
            name="haunting_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
