# Generated by Django 5.2.6 on 2025-09-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0003_haunting_fk_hauntingtype_haunting_fk_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="haunting",
            name="haunting_type",
        ),
        migrations.AddField(
            model_name="haunting",
            name="haunting_behavior",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="haunting",
            name="haunting_deathstory",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="haunting",
            name="haunting_discoveryofhaunting",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="haunting",
            name="haunting_physicaldetails",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="haunting",
            name="haunting_timeline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="location_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="location_namecurrent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="location_nameformer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
