# Generated by Django 5.2.6 on 2025-09-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0004_remove_haunting_haunting_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("id_contributor", models.AutoField(primary_key=True, serialize=False)),
                ("contributor_firstname", models.TextField(blank=True, null=True)),
                ("contributor_secondname", models.TextField(blank=True, null=True)),
                ("contributor_notes", models.TextField(blank=True, null=True)),
                ("contributor_active", models.TextField(blank=True, null=True)),
                ("contributor_photograph", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "contributor",
                "managed": True,
            },
        ),
    ]
