# Generated by Django 5.2.6 on 2025-09-22 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HauntedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your haunting story', max_length=200)),
                ('story', models.TextField(help_text='Detailed description of your paranormal experience')),
                ('author', models.CharField(blank=True, help_text='Your name (optional)', max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate of the haunting location', max_digits=9, validators=[django.core.validators.MinValueValidator(38.9), django.core.validators.MaxValueValidator(39.1)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate of the haunting location', max_digits=9, validators=[django.core.validators.MinValueValidator(-95.4), django.core.validators.MaxValueValidator(-95.1)])),
                ('date_occurred', models.DateField(blank=True, help_text='When did this haunting occur?', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, help_text='Admin approval for public display')),
                ('featured', models.BooleanField(default=False, help_text='Featured story')),
                ('submitter_email', models.EmailField(blank=True, help_text='Contact email (not displayed publicly)', max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Haunted Story',
                'verbose_name_plural': 'Haunted Stories',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
